services:
  postgres:
    image: postgres:16
    container_name: feedbacks-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-feedbacks}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-feedbacks}"]
      interval: 5s
      timeout: 5s
      retries: 5

